# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Failure'), (3, 'Half Filled'), (4, 'Not Reachable'), (5, 'Wrong No'), (6, 'Trash')], default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
    ]
